export { default as HomePage } from './Home/HomePage';
export { default as MatchesPage } from './Matches/MatchesPage';
export { default as TeamPage } from './Teams/TeamPage';
export { default as TeamListPage } from './Teams/TeamListPage';
export { default as TournamentsPage } from './Tournaments/TournamentsPage';
export { default as LoginPage } from './Login/LoginPage';
export { default as SignUpPage } from './SignUp/SignUpPage';
export { default as SettingsPage } from './Settings/SettingsPage';
export { default as UserPage } from './User/UserPage';
export { default as BetsPage } from './Bets/BetsPage';
export { default as MatchPage } from './Matches/MatchPage';
export { default as GameListPage } from './Games/GameListPage';
export { default as ChangePasswordPage } from './ChangePassword/ChangePasswordPage';
export { default as ForgotPasswordPage } from './ForgotPassword/ForgotPasswordPage';
export { default as VerifyEmailPage } from './Login/VerifyEmailPage'
export { default as NotFoundPage } from './Errors/NotFoundPage';
export { default as AboutPage } from './About/AboutPage';
export { default as TermsOfUsePage } from './TermsOfUse/TermsOfUsePage';

